# Generated by Django 5.1.3 on 2024-11-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=50)),
                ('price_product', models.FloatField()),
                ('image_product', models.CharField(max_length=50)),
            ],
        ),
    ]
