# Generated by Django 5.1.3 on 2024-11-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
